### ISSUE TITLE
404

### ISSUE THREAD

**Issue by kalebmmm** [TheMrGong/MCLeaksApiClient#1]
Used exactly as shown in the example, I get this. As tested in a rest client, it seems to be an issue with the server, not the code, but any enlightenment would help.

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Failed : HTTP error code : 404
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at me.gong.mcleaks.MCLeaksAPIImpl.lambda$checkAccount$0(MCLeaksAPIImpl.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed : HTTP error code : 404
	at me.gong.mcleaks.MCLeaksAPIImpl$McleaksFetcher.load(MCLeaksAPIImpl.java:79)
	at me.gong.mcleaks.MCLeaksAPIImpl$McleaksFetcher.load(MCLeaksAPIImpl.java:61)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 9 more
```

**Comment by TheMrGong** [comment]
I'm able to replicate the issue and working to resolve it. Must be due to
removing API keys.

**Comment by TheMrGong** [comment]
Ah, turns out the SRV record isn't working as intended. I've changed some
settings and am waiting for it to propagate
