### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by kalebmmm** [TheMrGong/MCLeaksApiClient#2]
This code I have results in a 500 Internal Server Error. I have no idea why, I've tried everything else. What I'm sending to the server is identical to what the API uses.

```
HttpURLConnection conn = (HttpURLConnection) new URL("http://themrgong.xyz:6970/api/v1/ismcleaks").openConnection();

            conn.setDoOutput(true);
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json; charset=UTF-8");

            JSONObject request = new JSONObject();
            request.put("name", e.getName());
            String data = request.toJSONString();
            System.out.println(data);

            OutputStream os = conn.getOutputStream();
            os.write(data.getBytes());
            os.flush();

            if (conn.getResponseCode() != HttpURLConnection.HTTP_OK) {
                System.out.println(conn.getResponseCode() + ", " + conn.getResponseMessage());
                return;
```

The same thing works fine in a rest client
http://prntscr.com/erdzwt

**Comment by kalebmmm** [comment]
Using the API doesn't seem to work either, unless it wasn't updated on Jitpack

**Comment by TheMrGong** [comment]
Have you changed the version to the latest one?

**Comment by kalebmmm** [comment]
Yes, this code (Using 1.3)
```
public static void main(String[] args) {
        MCLeaksAPI.Builder b = MCLeaksAPI.builder();
        b.expireAfter(10, TimeUnit.MINUTES);
        b.threadCount(1);
        MCLeaksAPI api = b.build();

        api.checkAccount("BwA_BOOMSTICK", isMCLeaks ->
                System.out.println("Got: " + isMCLeaks), Throwable::printStackTrace);
}

```

Results in the following:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Failed : HTTP error code : 500
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at me.gong.mcleaks.MCLeaksAPIImpl.lambda$checkAccount$0(MCLeaksAPIImpl.java:36)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed : HTTP error code : 500
	at me.gong.mcleaks.MCLeaksAPIImpl$McleaksFetcher.load(MCLeaksAPIImpl.java:79)
	at me.gong.mcleaks.MCLeaksAPIImpl$McleaksFetcher.load(MCLeaksAPIImpl.java:61)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 9 more
```

Still works find in Wiztools.org's RESTClient:
http://prntscr.com/eroerc

**Comment by TheMrGong** [comment]
Must be the nginx I setup recently. I'll see what I can do tomorrow,
already off my PC. Sorry for any inconveniences. 

Actually, you might've been trying to use the API when I was doing some maintenance. Not sure if it will work now but I don't foresee me doing maintenance on the server any time soon, meaning it should be up.

**Comment by TheMrGong** [comment]
I'm not currently able to reproduce any issues at the moment. Can you check on your end and see if the issue still occurs?

**Comment by kalebmmm** [comment]
Still getting HTTP 500

**Comment by TheMrGong** [comment]
Try one more time, I believe it causes an error in my console. I'll see the error tomorrow and be able to investigate it further. Again, apologies for all this.

**Comment by TheMrGong** [comment]
I've updated the server to show me what your requestBody is, try sending another request. I noticed when you send a request it causes a null pointer and am investigated if somehow the data is being corrupted.

**Comment by TheMrGong** [comment]
Also what operating system are you running this from?

**Comment by TheMrGong** [comment]
The issue may lie in that the charset for getBytes wasn't specified and your os uses a charset inconsistent with the one the server uses. I'll release a fix when i get home.

**Comment by kalebmmm** [comment]
Sorry, I've been gone. I'm using windows and UTF-8, I'll try it in a bit.

**Comment by TheMrGong** [comment]
It's alright, I'll be releasing v1.4 within 16 hours

**Comment by TheMrGong** [comment]
Let me know if the issue still persists, I have one idea left in that case.
